clone_depth: 5

environment:
  access_token:
    secure: DAP/zdV4e2KWw6NSLEORAhVXT3u4dk3pKuT6z5CWlQoi1NWnNhLLXwBBt1nNSsnx
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  # - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - pip install -r requirements.txt

build_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO%
  - cd %STATIC_SITE_REPO%
  - if [ "`ls photo/pic/`" != "" ]; then
  # - "%PYTHON%\\python.exe compress.py"
  # - "%PYTHON%\\python.exe make-json.py"
  - python compress.py
  - python make-json.py

on_success:
  - git add -A
  - git commit -m "Update Static Site"
  - git push origin %TARGET_BRANCH%
  - appveyor AddMessage "Static Site Updated"