clone_depth: 5

environment:
  access_token:
    secure: DAP/zdV4e2KWw6NSLEORAhVXT3u4dk3pKuT6z5CWlQoi1NWnNhLLXwBBt1nNSsnx
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - pip install Pillow
  - pip install opencv-python

build_script:
  - python compress.py
  - python make-json.py

on_success:
  - git config --global credential.helper store
  # - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git add -A
  - git commit -m "Update Static Site"
  - git push origin %TARGET_BRANCH%
  - appveyor AddMessage "Static Site Updated"